---
- hosts: all
  sudo: yes
  roles:
    - docker-confirm
    - hello

  tasks:
    - name: front-rev-proxy
      docker:
        name: front-rev-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        ports: "80:80"
        image: jwilder/nginx-proxy
        name: nginx-proxy

    - name: jenkins-master ~ 689 MB
      docker:
        env: "VIRTUAL_HOST=jenkins.{{ domain }},VIRTUAL_PORT=8080,JAVA_OPTS=-Duser.timezone=EET -Dfile.encoding=UTF8"
        volumes: /etc/localtime:/etc/localtime:ro
        ports: "8080:8080,50000:50000"
        image: sirkkalap/jenkins-swarm-w-git-manual:latest
        name: jenkins-master

    - name: dev-tykkays20 ~ 52 MB
      docker:
        name: dev-tykkays20
        volumes:
            - /data/hello/usr/share/nginx/html:/usr/share/nginx/html:ro
        env: "VIRTUAL_HOST=dev.{{ domain }}"
        image: nginx:latest

    - name: test-tykkays20 (should be cached now)
      docker:
        name: test-tykkays20
        volumes:
            - /data/hello/usr/share/nginx/html:/usr/share/nginx/html:ro
        env: "VIRTUAL_HOST=test.{{ domain }}"
        image: nginx:latest

    - name: qa-tykkays20 (should be cached now)
      docker:
        name: qa-tykkays20
        volumes:
            - /data/hello/usr/share/nginx/html:/usr/share/nginx/html:ro
        env: "VIRTUAL_HOST=qa.{{ domain }}"
        image: nginx:latest

    - name: prod-tykkays20 (should be cached now)
      docker:
        name: prod-tykkays20
        volumes:
            - /data/hello/usr/share/nginx/html:/usr/share/nginx/html:ro
        env: "VIRTUAL_HOST=prod.{{ domain }}"
        image: nginx:latest
